### ISSUE TITLE
"npm run dev-server" failed in ubuntu

### ISSUE THREAD

**Issue by byteblock-labs** [jgudo/ecommerce-react#41]
Entrypoint main = js/main.bundle.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./src/index.jsx 52 bytes {main} [built]
[./node_modules/@babel/polyfill/lib/index.js] 686 bytes {main} [built]
[./node_modules/@babel/polyfill/lib/noConflict.js] 567 bytes {main} [built]
[./node_modules/@babel/polyfill/node_modules/core-js/library/fn/global.js] 87 bytes {main} [built]
[./node_modules/normalize.css/normalize.css] 914 bytes {main} [built] [failed] [1 error]
[./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[./node_modules/react-phone-input-2/lib/style.css] 914 bytes {main} [built] [failed] [1 error]
[./node_modules/react/index.js] 190 bytes {main} [built]
[./node_modules/webfontloader/webfontloader.js] 12.2 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./src/index.jsx] 1.49 KiB {main} [built]
    + 2594 hidden modules

ERROR in ./node_modules/normalize.css/normalize.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleError: Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Missing binding /root/ecommerce-react/node_modules/node-sass/vendor/linux-x64-83/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 14.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 14.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at Object.emitError (/root/ecommerce-react/node_modules/webpack/lib/NormalModule.js:173:6)
    at getSassImplementation (/root/ecommerce-react/node_modules/sass-loader/dist/utils.js:59:21)
    at Object.loader (/root/ecommerce-react/node_modules/sass-loader/dist/index.js:35:59)
 @ ./src/index.jsx 2:0-37
 @ multi @babel/polyfill ./src/index.jsx

ERROR in ./src/styles/style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleError: Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Missing binding /root/ecommerce-react/node_modules/node-sass/vendor/linux-x64-83/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 14.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 14.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at Object.emitError (/root/ecommerce-react/node_modules/webpack/lib/NormalModule.js:173:6)
    at getSassImplementation (/root/ecommerce-react/node_modules/sass-loader/dist/utils.js:59:21)
    at Object.loader (/root/ecommerce-react/node_modules/sass-loader/dist/index.js:35:59)
 @ ./src/index.jsx 8:0-27
 @ multi @babel/polyfill ./src/index.jsx

ERROR in ./node_modules/react-phone-input-2/lib/style.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleError: Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Missing binding /root/ecommerce-react/node_modules/node-sass/vendor/linux-x64-83/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 14.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 14.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at Object.emitError (/root/ecommerce-react/node_modules/webpack/lib/NormalModule.js:173:6)
    at getSassImplementation (/root/ecommerce-react/node_modules/sass-loader/dist/utils.js:59:21)
    at Object.loader (/root/ecommerce-react/node_modules/sass-loader/dist/index.js:35:59)
 @ ./src/index.jsx 5:0-43
 @ multi @babel/polyfill ./src/index.jsx
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.html] 657 bytes {HtmlWebpackPlugin_0} [built]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--5-1!node_modules/group-css-media-queries-loader/lib/index.js!node_modules/sass-loader/dist/cjs.js??ref--5-3!node_modules/normalize.css/normalize.css:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js?!./node_modules/group-css-media-queries-loader/lib/index.js!./node_modules/sass-loader/dist/cjs.js?!./node_modules/normalize.css/normalize.css] ./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/group-css-media-queries-loader/lib!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./node_modules/normalize.css/normalize.css 739 bytes {mini-css-extract-plugin} [built] [failed] [2 errors]

    ERROR in ./node_modules/normalize.css/normalize.css (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/group-css-media-queries-loader/lib!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./node_modules/normalize.css/normalize.css)
    Module Error (from ./node_modules/sass-loader/dist/cjs.js):
    Missing binding /root/ecommerce-react/node_modules/node-sass/vendor/linux-x64-83/binding.node
    Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 14.x

    Found bindings for the following environments:
      - Windows 64-bit with Node.js 14.x

    This usually happens because your environment has changed since running `npm install`.
    Run `npm rebuild node-sass` to download the binding for your current environment.

    ERROR in ./node_modules/normalize.css/normalize.css (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/group-css-media-queries-loader/lib!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./node_modules/normalize.css/normalize.css)
    Module build failed (from ./node_modules/group-css-media-queries-loader/lib/index.js):
    Error: PostCSS received undefined instead of CSS string
        at new Input (/root/ecommerce-react/node_modules/postcss/lib/input.js:38:13)
        at parse (/root/ecommerce-react/node_modules/postcss/lib/parse.js:13:15)
        at new LazyResult (/root/ecommerce-react/node_modules/postcss/lib/lazy-result.js:64:16)
        at Processor.<anonymous> (/root/ecommerce-react/node_modules/postcss/lib/processor.js:142:12)
        at Processor.process (/root/ecommerce-react/node_modules/postcss/lib/processor.js:121:23)
        at Object.GroupCssMediaQueriesLoader (/root/ecommerce-react/node_modules/group-css-media-queries-loader/lib/index.js:21:12)
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--5-1!node_modules/group-css-media-queries-loader/lib/index.js!node_modules/sass-loader/dist/cjs.js??ref--5-3!node_modules/react-phone-input-2/lib/style.css:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js?!./node_modules/group-css-media-queries-loader/lib/index.js!./node_modules/sass-loader/dist/cjs.js?!./node_modules/react-phone-input-2/lib/style.css] ./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/group-css-media-queries-loader/lib!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./node_modules/react-phone-input-2/lib/style.css 739 bytes {mini-css-extract-plugin} [built] [failed] [2 errors]

    ERROR in ./node_modules/react-phone-input-2/lib/style.css (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/group-css-media-queries-loader/lib!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./node_modules/react-phone-input-2/lib/style.css)
    Module Error (from ./node_modules/sass-loader/dist/cjs.js):
    Missing binding /root/ecommerce-react/node_modules/node-sass/vendor/linux-x64-83/binding.node
    Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 14.x

    Found bindings for the following environments:
      - Windows 64-bit with Node.js 14.x

    This usually happens because your environment has changed since running `npm install`.
    Run `npm rebuild node-sass` to download the binding for your current environment.

    ERROR in ./node_modules/react-phone-input-2/lib/style.css (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/group-css-media-queries-loader/lib!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./node_modules/react-phone-input-2/lib/style.css)
    Module build failed (from ./node_modules/group-css-media-queries-loader/lib/index.js):
    Error: PostCSS received undefined instead of CSS string
        at new Input (/root/ecommerce-react/node_modules/postcss/lib/input.js:38:13)
        at parse (/root/ecommerce-react/node_modules/postcss/lib/parse.js:13:15)
        at new LazyResult (/root/ecommerce-react/node_modules/postcss/lib/lazy-result.js:64:16)
        at Processor.<anonymous> (/root/ecommerce-react/node_modules/postcss/lib/processor.js:142:12)
        at Processor.process (/root/ecommerce-react/node_modules/postcss/lib/processor.js:121:23)
        at Object.GroupCssMediaQueriesLoader (/root/ecommerce-react/node_modules/group-css-media-queries-loader/lib/index.js:21:12)
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--5-1!node_modules/group-css-media-queries-loader/lib/index.js!node_modules/sass-loader/dist/cjs.js??ref--5-3!src/styles/style.scss:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js?!./node_modules/group-css-media-queries-loader/lib/index.js!./node_modules/sass-loader/dist/cjs.js?!./src/styles/style.scss] ./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/group-css-media-queries-loader/lib!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./src/styles/style.scss 739 bytes {mini-css-extract-plugin} [built] [failed] [2 errors]

    ERROR in ./src/styles/style.scss (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/group-css-media-queries-loader/lib!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./src/styles/style.scss)
    Module Error (from ./node_modules/sass-loader/dist/cjs.js):
    Missing binding /root/ecommerce-react/node_modules/node-sass/vendor/linux-x64-83/binding.node
    Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 14.x

    Found bindings for the following environments:
      - Windows 64-bit with Node.js 14.x

    This usually happens because your environment has changed since running `npm install`.
    Run `npm rebuild node-sass` to download the binding for your current environment.

    ERROR in ./src/styles/style.scss (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/group-css-media-queries-loader/lib!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./src/styles/style.scss)
    Module build failed (from ./node_modules/group-css-media-queries-loader/lib/index.js):
    Error: PostCSS received undefined instead of CSS string
        at new Input (/root/ecommerce-react/node_modules/postcss/lib/input.js:38:13)
        at parse (/root/ecommerce-react/node_modules/postcss/lib/parse.js:13:15)
        at new LazyResult (/root/ecommerce-react/node_modules/postcss/lib/lazy-result.js:64:16)
        at Processor.<anonymous> (/root/ecommerce-react/node_modules/postcss/lib/processor.js:142:12)
        at Processor.process (/root/ecommerce-react/node_modules/postcss/lib/processor.js:121:23)
        at Object.GroupCssMediaQueriesLoader (/root/ecommerce-react/node_modules/group-css-media-queries-loader/lib/index.js:21:12)
ℹ ｢wdm｣: Failed to compile.

how do i solve this issue?

**Comment by jgudo** [comment]
Have you tried running 'npm rebuild node-sass' as suggested by the error
log?

**Comment by byteblock-labs** [comment]
tried with the below steps:
# npm install
# npm rebuild node-sass
# npm run dev-server

found same issue? did u ever built in Ubuntu?

**Comment by jgudo** [comment]
I built the site in Windows env, unfortunately.
How about deleting the node-sass folder inside your node_modules then run
npm install again?

**Comment by byteblock-labs** [comment]
Windows build works fine. Please support Linux also. Most deployments happen in CentOS/Ubuntu.

**Comment by jgudo** [comment]
Thanks for the input! Will take care of  that problem during my free time.
This issue is clearly on the node-sass binding for your environment. Surely
there's a solution for that.
Found this on stackoverflow
https://stackoverflow.com/questions/37986800/node-sass-couldnt-find-a-binding-for-your-current-environment

maybe it could help.

**Comment by byteblock-labs** [comment]
nop, it is a compilation issue.

**Comment by jgudo** [comment]
Yes. It won't compile because there's an issue with node-sass binding for
your environment.
