### ISSUE TITLE
Blank white screen

### ISSUE THREAD

**Issue by Davidjunior256** [jgudo/ecommerce-react#45]
Hey, your work is amazing.
I got an issue,
I did npm install,
npm run dev-sever

It accepted to run on a localhost but shows a blank white 

`USER@DavidJrGoogle MINGW64 /d/ecommerce-react
$ npm run dev-server

> ecommerce-react@1.2.0 dev-server D:\ecommerce-react
> webpack serve --config webpack/dev.config.js

× ｢wds｣:  Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1500:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:10) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
group-css-media-queries: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
× ｢wdm｣: assets by path static/ 4.94 MiB
  assets by path static/*.png 1.37 MiB 20 assets
  assets by path static/*.jpg 3.57 MiB 2 assets
assets by path images/ 1.9 MiB
  assets by path images/*.png 1.79 MiB 5 assets
  assets by path images/*.jpg 113 KiB
    asset images/defaultBanner.accdc757f2c48d61f24c4fbcef2742fd.jpg 95.1 KiB [emitted] [immutable] [from: src/images/defaultBanner.jpg] (auxiliary name: main)
    asset images/defaultAvatar.4e9edb2a624547982816014bf128fcd5.jpg 18.1 KiB [emitted] [immutable] [from: src/images/defaultAvatar.jpg] (auxiliary name: main)
assets by path js/*.js 14.5 MiB
  asset js/main.bundle.js 14.5 MiB [emitted] (name: main)
  asset js/src_views_account_components_UserAccountTab_jsx.bundle.js 11.2 KiB [emitted]
  asset js/src_views_account_components_UserWishListTab_jsx.bundle.js 2.63 KiB [emitted]
  asset js/src_views_account_components_UserOrdersTab_jsx.bundle.js 2.59 KiB [emitted]
asset index.html 478 bytes [emitted]
orphan modules 1.3 MiB [orphan] 1621 modules
runtime modules 6.44 KiB 13 modules
built modules 5.13 MiB [built]
  modules by path ./node_modules/ 4.77 MiB 810 modules
  modules by path ./src/ 370 KiB 123 modules
  ./static/logo-wordmark.png 101 bytes [built] [code generated]

ERROR in ./node_modules/normalize.css/normalize.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
D:\ecommerce-react\node_modules\sass-loader\dist\index.js:7
export { __default as default };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\ecommerce-react\node_modules\sass-loader\dist\cjs.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at processResult (D:\ecommerce-react\node_modules\webpack\lib\NormalModule.js:751:19)
    at D:\ecommerce-react\node_modules\webpack\lib\NormalModule.js:853:5
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:185:11
    at loadLoader (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:33:11)
    at iteratePitchingLoaders (D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at iteratePitchingLoaders (D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:178:10)
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:189:18
    at handleResult (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:53:2)
    at loadLoader (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:35:10)
 @ ./src/index.jsx 2:0-37

ERROR in ./node_modules/react-phone-input-2/lib/style.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
D:\ecommerce-react\node_modules\sass-loader\dist\index.js:7
export { __default as default };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\ecommerce-react\node_modules\sass-loader\dist\cjs.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at processResult (D:\ecommerce-react\node_modules\webpack\lib\NormalModule.js:751:19)
    at D:\ecommerce-react\node_modules\webpack\lib\NormalModule.js:853:5
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:185:11
    at loadLoader (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:33:11)
    at iteratePitchingLoaders (D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at iteratePitchingLoaders (D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:178:10)
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:189:18
    at handleResult (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:53:2)
    at loadLoader (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:35:10)
 @ ./src/index.jsx 5:0-43

ERROR in ./src/styles/style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
D:\ecommerce-react\node_modules\sass-loader\dist\index.js:7
export { __default as default };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\ecommerce-react\node_modules\sass-loader\dist\cjs.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at processResult (D:\ecommerce-react\node_modules\webpack\lib\NormalModule.js:751:19)
    at D:\ecommerce-react\node_modules\webpack\lib\NormalModule.js:853:5
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:185:11
    at loadLoader (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:33:11)
    at iteratePitchingLoaders (D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at iteratePitchingLoaders (D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:178:10)
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:189:18
    at handleResult (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:53:2)
    at loadLoader (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:35:10)
 @ ./src/index.jsx 8:0-27

3 ERRORS in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.61.0 compiled with 6 errors in 75676 ms
i ｢wdm｣: Failed to compile.
i ｢wdm｣: Compiling...
× ｢wdm｣: assets by status 21.3 MiB [cached] 33 assets
asset index.html 478 bytes [emitted]
cached modules 6.43 MiB (javascript) 6.44 KiB (runtime) [cached] 2625 modules
javascript modules 117 bytes
  ./node_modules/normalize.css/normalize.css 39 bytes [built] [1 error]
  ./node_modules/react-phone-input-2/lib/style.css 39 bytes [built] [1 error]
  ./src/styles/style.scss 39 bytes [built] [1 error]

ERROR in ./node_modules/normalize.css/normalize.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
D:\ecommerce-react\node_modules\sass-loader\dist\index.js:7
export { __default as default };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\ecommerce-react\node_modules\sass-loader\dist\cjs.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at processResult (D:\ecommerce-react\node_modules\webpack\lib\NormalModule.js:751:19)
    at D:\ecommerce-react\node_modules\webpack\lib\NormalModule.js:853:5
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:185:11
    at loadLoader (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:33:11)
    at iteratePitchingLoaders (D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at iteratePitchingLoaders (D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:178:10)
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:189:18
    at handleResult (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:53:2)
    at loadLoader (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:35:10)
 @ ./src/index.jsx 2:0-37

ERROR in ./node_modules/react-phone-input-2/lib/style.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
D:\ecommerce-react\node_modules\sass-loader\dist\index.js:7
export { __default as default };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\ecommerce-react\node_modules\sass-loader\dist\cjs.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at processResult (D:\ecommerce-react\node_modules\webpack\lib\NormalModule.js:751:19)
    at D:\ecommerce-react\node_modules\webpack\lib\NormalModule.js:853:5
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:185:11
    at loadLoader (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:33:11)
    at iteratePitchingLoaders (D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at iteratePitchingLoaders (D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:178:10)
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:189:18
    at handleResult (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:53:2)
    at loadLoader (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:35:10)
 @ ./src/index.jsx 5:0-43

ERROR in ./src/styles/style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
D:\ecommerce-react\node_modules\sass-loader\dist\index.js:7
export { __default as default };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\ecommerce-react\node_modules\sass-loader\dist\cjs.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at processResult (D:\ecommerce-react\node_modules\webpack\lib\NormalModule.js:751:19)
    at D:\ecommerce-react\node_modules\webpack\lib\NormalModule.js:853:5
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:185:11
    at loadLoader (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:33:11)
    at iteratePitchingLoaders (D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at iteratePitchingLoaders (D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:178:10)
    at D:\ecommerce-react\node_modules\loader-runner\lib\LoaderRunner.js:189:18
    at handleResult (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:53:2)
    at loadLoader (D:\ecommerce-react\node_modules\loader-runner\lib\loadLoader.js:35:10)
 @ ./src/index.jsx 8:0-27

3 ERRORS in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.61.0 compiled with 6 errors in 1985 ms
i ｢wdm｣: Failed to compile.

`
> 

> screen

**Comment by hemcharan22** [comment]
+1

**Comment by hemcharan22** [comment]
found the problem . for me node-sass module is missing you can install it using the command
`npm i node-sass`

**Comment by jekabso21** [comment]
> found the problem . for me node-sass module is missing you can install it using the command `npm i node-sass`


the problem did not fix it for me :(
